### ISSUE TITLE
What is this repo about?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [TheChernoCommunity/UmikoBot#46]
No info in readme, no info about it in the repo's description, no issue explaining it...

**Comment by Gaztin** [comment]
It's a community-driven Discord bot. We keep all our community projects in this organization.
May I ask how you found the repo in the first place?

**Comment by WhiteBlackGoose** [comment]
> It's a community-driven Discord bot.

For what? I got the fact that it's a bot from the name...

> May I ask how you found the repo in the first place?

Sure. GH's recommendations :). Although I don't develop any bots.

**Comment by NotJustSid** [comment]
> For what?

Just a fun bot we primarily use on TheCherno Discord server.

**Comment by Gaztin** [comment]
> Sure. GH's recommendations :). Although I don't develop any bots.

Oh wow I didn't think about GitHub potentially recommending this repository to anyone outside the community.

> For what? I got the fact that it's a bot from the name...

We're a community revolving around the Game Engine Youtuber: [TheCherno](https://www.youtube.com/user/TheChernoProject)!

**Comment by WhiteBlackGoose** [comment]
Alright… I see XD
