### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by JacoMalan1** [TheChernoCommunity/UmikoBot#53]
When running the bot, the bot crashes whenever a call to `getUserData()` is made.

This only happens when the relevant config files in `res/config/` don't exist.

**Comment by Gaztin** [comment]
Thanks for pointing it out. A quick look in the `getUserData()` function leads me to believe that this is the cause of the bug. The iterator type is not a reference, and we're returning a reference to a local variable. See https://github.com/TheChernoCommunity/UmikoBot/blob/b7153e71f04c4e0faa68d4038badc5c08008f767/src/modules/CurrencyModule.h#L169

**Comment by NotJustSid** [comment]
That's weird; I remember I returned the thing by value instead of reference.

**Comment by NotJustSid** [comment]
Well, a quick git blame shows that @FahimFuad changed it.

**Comment by JacoMalan1** [comment]
I fixed it in my PR.
